Class components branch
Deadricss5/marvel-db-app pull request #6
Opened 2021-08-23 07:34 UTC by Deadricss5

Переписал компоненты на классы.

2021-09-06 15:31 UTC, alinalaktionova requested changes
Too many duplications through all code

2021-09-06 15:31 UTC, alinalaktionova commented on src/types/types.ts
> +
why empty string is here?

2021-09-06 15:31 UTC, alinalaktionova commented on src/types/types.ts
> +export interface serverRes {
bad naming

2021-09-06 15:31 UTC, alinalaktionova commented on src/types/types.ts
> +export interface heroes {
this interface almost the same as serverRes

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
> +  const keyPublic = '0eae8530cd8dcf4e3f02d5aea4380a1f';
move api keys to .env variables

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
>    const hash: string = md5(ts + keyPrivate + keyPublic);
for what?????

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
>    const ts: number = Date.now();
naming is bad. Why variable number is a date in fact?

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
> +    this.baseURL = 'https://gateway.marvel.com:443/v1/public';
baseUrl should be as a constant in separate file with all api requests

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
>      return axios.get(
move axios requests to the separate file

2021-09-06 15:31 UTC, alinalaktionova commented on src/api/api.ts
>      return axios.get(
the same

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/card/index.tsx
> +import Typography from '@material-ui/core/Typography';
I think you can use import destructuring here to reduce duplication

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/card/index.tsx
> +    <Zoom in={Boolean(id)} timeout={timeout}>
in={Boolean(id)} is not understandable

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/hero_details/index.tsx
> +                <a href={el.urls[0].url} target="_blank" rel="noreferrer">
too strange el.urls[0].url and not clear. Move to var or rewrite

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/hero_details/types.ts
> +  urls: [ { url: string } ];
array of objects with url field? why so complicated?

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/pagination/index.tsx
> +  onChange: (event: React.ChangeEvent<unknown>, page: number) => void;
unknown is not a good practice, use right type

2021-09-06 15:31 UTC, alinalaktionova commented on src/components/pagination/pagination.css
> +.pagination {
why do you create a file with 3 strings?:)

2021-09-06 15:31 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +  async componentDidUpdate(prevProps: Readonly<IProps>, prevState: Readonly<IState>): Promise<void> {
too many duplications in this method. rewrite and read about DRY principle

2021-09-06 15:31 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +    return MarvelApi.getHeroByName(name, offset).then(
the same part of code as in above method

2021-09-06 18:00 UTC, Deadricss5 commented on src/api/api.ts
> +  const keyPublic = '0eae8530cd8dcf4e3f02d5aea4380a1f';
fixed

2021-09-06 18:02 UTC, Deadricss5 commented on src/types/types.ts
> +
I tried to separate code visually. Fixed it.

2021-09-07 16:52 UTC, Deadricss5 commented on src/api/api.ts
>    const hash: string = md5(ts + keyPrivate + keyPublic);
I exceeded the requests limit and make the decision not wait for 24 hours and create a new account

2021-09-07 16:57 UTC, Deadricss5 commented on src/api/api.ts
>    const ts: number = Date.now();
1. Change name of the variable.
2. Because it's a timestamp and timestamp has type number.

2021-09-07 17:23 UTC, Deadricss5 commented on src/components/pagination/pagination.css
> +.pagination {
I was thinking about the future, maybe I should add more styles. I will remove it.

2021-09-08 11:23 UTC, alinalaktionova requested changes

2021-09-08 11:23 UTC, alinalaktionova commented on src/api/.env/variables.ts
> +export const keyPublic = '0eae8530cd8dcf4e3f02d5aea4380a1f';
it is not env variable:) Read about this please

2021-09-08 11:23 UTC, alinalaktionova commented on src/api/.env/variables.ts
> +export const baseURL = 'https://gateway.marvel.com:443/v1/public';
baseUrl shouldn't be in .env file

2021-09-08 11:23 UTC, alinalaktionova commented on src/api/api.ts
>  function generateApiKey(): string {
no need in this method at all

2021-09-09 12:49 UTC, alinalaktionova commented on .env
> +REACT_APP_BASE_URL=https://gateway.marvel.com:443/v1/public
base Url is not env variable

2021-09-09 13:32 UTC, alinalaktionova approved these changes

2021-09-09 17:48 UTC, merged