Redux branch
Deadricss5/marvel-db-app pull request #8
Opened 2021-09-14 19:18 UTC by Deadricss5

add redux to project

2021-09-15 15:28 UTC, alinalaktionova requested changes
Read about async actions in Redux please. And about redux state architecture

2021-09-15 15:28 UTC, alinalaktionova commented on src/components/hero_details/index.tsx
> +    const { dispatch } = this.props;
you can combine with 10 line

2021-09-15 15:28 UTC, alinalaktionova commented on src/components/hero_details/index.tsx
> +                <a href={el.urls[0].url} target="_blank" rel="noreferrer" key={el.id}>
so strange logic for getting url

2021-09-15 15:28 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +  // eslint-disable-next-line no-useless-constructor
why disable eslint????

2021-09-15 15:28 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +        type: 'HEROES_REQUEST',
types should be constant

2021-09-15 15:28 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +    if (typeof pages === 'number') {
which else type can be here?

2021-09-15 15:28 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +  return state;
you can remove return statement and {} braces

2021-09-15 15:28 UTC, alinalaktionova commented on src/redux/sagas/index.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
you shouldn't disable eslint in any case

2021-09-15 15:28 UTC, alinalaktionova commented on src/types/types.ts
> +export type DispatchType = (args: SET_HEROES_ACTION) => SET_HEROES_ACTION
what?????

2021-09-15 15:28 UTC, alinalaktionova commented on src/redux/sagas/index.ts
> +  return request.data.data.results[0];
why 1st element of array? do you get several heroes by id?

2021-09-15 15:28 UTC, alinalaktionova commented on src/redux/reducers/index.ts
> +    case 'HERO_DETAILS_REQUEST_SUCCEEDED':
pointless action )))

2021-09-15 15:28 UTC, alinalaktionova commented on src/types/types.ts
> +export interface IState {
almost the same as interface IAction

2021-09-15 17:56 UTC, Deadricss5 commented on src/redux/sagas/index.ts
> +  return request.data.data.results[0];
No, if I just return results it will be an array with one item(object) that's why I return first item of the array.

2021-09-15 17:59 UTC, Deadricss5 commented on src/redux/reducers/index.ts
> +    case 'HERO_DETAILS_REQUEST_SUCCEEDED':
why?

2021-09-15 18:04 UTC, Deadricss5 commented on src/containers/search_and_cards/container.tsx
> +    if (typeof pages === 'number') {
TS think it can be undefined.

2021-09-15 18:08 UTC, Deadricss5 commented on src/containers/search_and_cards/container.tsx
> +  // eslint-disable-next-line no-useless-constructor
Because it's scold about useless constructor

2021-09-17 20:21 UTC, alinalaktionova requested changes

2021-09-17 20:21 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +  dispatchAction = (lifeCycle: string, prevProps?: Readonly<IProps>): void => {
not a good name for method and strange input params

2021-09-17 20:21 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +    this.dispatchAction('DidMount');
very strange logic

2021-09-17 20:21 UTC, alinalaktionova commented on src/redux/actions/actionTypes.ts
> +  ON_REQUEST_HEROES_START= 'REQUEST_HEROES_START',
constant should have the same name as string actually, without any prepositions

2021-09-17 20:21 UTC, alinalaktionova commented on src/redux/actions/heroesActions.ts
> +import { HeroesActionTypes } from './actionTypes';
why do you create a separate file for getting hero and heroes actions?

2021-09-17 20:21 UTC, alinalaktionova commented on src/redux/actions/actionTypes.ts
> +  ON_REQUEST_HEROES= 'REQUEST_HEROES',
there must be always 3 types for action (e.g. GET_HEROER REQUEST, GET_HEROES_SUCCESS, GET_HEROES_ERROR). This way you can understand in which phase the state is

2021-09-17 20:21 UTC, alinalaktionova commented on src/redux/sagas/index.ts
> +  yield put({ type: HeroActionTypes.ON_REQUEST_HERO_SUCCESS, payload: { hero, comics } });
where is error handling?

2021-09-20 13:22 UTC, alinalaktionova requested changes
Please add error handling actions to redux

2021-09-20 13:22 UTC, alinalaktionova commented on src/redux/actions/actionTypes.ts
> +  REQUEST_HEROES_SUCCESS= 'REQUEST_HEROES_SUCCESS',
where is error action again?)))

2021-09-21 16:01 UTC, alinalaktionova requested changes

2021-09-21 16:01 UTC, alinalaktionova commented on src/components/hero_details/types.ts
> +    heroLoading: boolean,
why heroLoading is 2 times

2021-09-21 16:01 UTC, alinalaktionova commented on src/components/hero_details/types.ts
> +  HeroDetails: {
shouldn't start from uppercase letter

2021-09-21 16:01 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +  Heroes?: {
the same, 1st letter should be small

2021-09-21 16:01 UTC, alinalaktionova commented on src/redux/reducers/HeroDetailsReducer.ts
> +        error: action.payload.error,
add heroLoading: false here

2021-09-21 16:01 UTC, alinalaktionova commented on src/redux/reducers/Heroes.ts
> +        error: action.payload.error,
the same with loading

2021-09-22 15:25 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +    if (heroes !== undefined) {
better to write if (heroes)

2021-09-22 15:25 UTC, alinalaktionova commented on src/containers/search_and_cards/container.tsx
> +      cards = heroes.cards;
can use destcructuring here

2021-09-22 15:46 UTC, alinalaktionova approved these changes

2021-09-22 17:13 UTC, merged